### ISSUE TITLE
User permission

### ISSUE THREAD

**Issue by Doanviethung4321** [Jalaljalili/vcenter-keycloak-sso#1]
Hello!

Thank you for your detailed and easy-to-follow guide. I was able to make it to the final step with very few issues. However, when I tried logging in with a Keycloak user, vSphere returned a message stating that the user does not have permission to access the system.

After doing some research, I found in VMware's documentation that after completing the configuration, I need to assign permissions to the user in the "Users and Groups" section under "Single Sign-On." The problem I'm facing is that it seems like vCenter is unable to retrieve user and group information from the OpenLDAP server in this case.

I've tried looking for answers online, but I haven't been able to find a solution. I hope you can provide some insights on this issue. Thank you very much!
![Screenshot 2024-09-17 094546](https://github.com/user-attachments/assets/e0031906-9e8e-484a-bb43-fb873f014062)

**Comment by Jalaljalili** [comment]
The issue you're encountering with vCenter not retrieving user and group information from the OpenLDAP server can be tricky. Here are a few steps and considerations that might help resolve this:

1. 
Verify LDAP Configuration: Ensure that your LDAP settings in vCenter are correctly configured. This includes the LDAP server address, base DN, and the correct binding credentials.
2. 
Check LDAP Schema: Make sure that the LDAP schema being used is compatible with vCenter. For instance, vCenter often expects certain attributes like uid for users and cn for groups. If your OpenLDAP schema differs, you might need to adjust it or map the attributes accordinglyhttps://www.virten.net/2020/07/how-to-configure-ldaps-authentication-in-vcenter-7-0/.
3. 
LDAP over SSL (LDAPS): If you're using LDAPS, verify that the SSL certificates are correctly installed and trusted by vCenter. You can test the connection using tools like openssl to ensure the certificates are validhttps://www.virten.net/2020/07/how-to-configure-ldaps-authentication-in-vcenter-7-0/.
4. 
User and Group Search Base: Double-check the search base for users and groups in your LDAP configuration. If these are not set correctly, vCenter might not be able to find the users and groups.

5. Permissions in vCenter: After ensuring that vCenter can communicate with the LDAP server, make sure to assign the necessary permissions to the users or groups in the "Users and Groups" section under "Single Sign-On"https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.authentication.doc/GUID-98B36135-CDC1-435C-8F27-5E0D0187FF7E.html.

1. Logs and Diagnostics: Check the vCenter logs for any errors or warnings related to LDAP. These logs can provide more detailed information about what might be going wrong.

**Comment by Doanviethung4321** [comment]
First of all, thank you for taking the time to look into the issue I’m facing, and I apologize for not providing more detailed information earlier. I have reviewed the points you suggested again to ensure I haven’t overlooked anything. I’m not using SSL, so there’s no issue there.

What really puzzles me is that when I add LDAP as an identity source, everything works as expected—vCenter can successfully retrieve users from my LDAP server. However, when I configure LDAP as the identity provider with the same connection details, vCenter is unable to retrieve any information, as shown in the attached screenshot above.

I apologize for my limited knowledge, but this is what I’m currently experiencing. I hope this gives you a clearer picture of the issue. Once again, thank you so much!

**Comment by Doanviethung4321** [comment]
and also my vcenter have not join any AD yet , not sure if it make any diferent

**Comment by Jalaljalili** [comment]
Don't worry, if you sure added the schema in OpenLDAP and restarted Vcenter at the end. Please check logs via Wireshark and get Vcenter network packets when logging or getting errors. There are many of info about Vcenter requirements.
